CREATE DATABASE COMERCIO_DB
GO
USE COMERCIO_DB
GO
--TABLAS
CREATE TABLE DBO.CLIENTE
	(ID INT PRIMARY KEY NOT NULL,
	NOMBRE VARCHAR(30) NOT NULL,
	APELLIDO VARCHAR(30) NOT NULL,
	ESTADO BIT NOT NULL DEFAULT 1)

CREATE TABLE DBO.PROVEEDOR
	(ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	NOMBRE VARCHAR(30) NOT NULL,
	ESTADO BIT NOT NULL DEFAULT 1)

CREATE TABLE DBO.MARCA
	(ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	NOMBRE VARCHAR(30) NOT NULL,
	ESTADO BIT NOT NULL DEFAULT 1)

CREATE TABLE DBO.CATEGORIA
	(ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	NOMBRE VARCHAR(30) NOT NULL,
	ESTADO BIT NOT NULL DEFAULT 1)

CREATE TABLE DBO.PRODUCTO
	(ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	NOMBRE VARCHAR(50) NOT NULL,
	IDMARCA INT FOREIGN KEY REFERENCES MARCA(ID),
	IDCATEGORIA INT FOREIGN KEY REFERENCES CATEGORIA(ID),
	IDPROVEEDOR INT NOT NULL FOREIGN KEY REFERENCES PROVEEDOR(ID),
	STOCK INT NOT NULL,
	STOCKMINIMO INT NOT NULL,
	PORCENTAJEGANANCIA DECIMAL(10,2) NOT NULL,
	ESTADO BIT NOT NULL DEFAULT 1)

CREATE TABLE DBO.VENTA
	(ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	IDCLIENTE INT FOREIGN KEY REFERENCES CLIENTE(ID),
	PRECIOFINAL MONEY NOT NULL)

	CREATE TABLE DBO.DETALLEVENTA
	(ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	IDPRODUCTO INT NOT NULL FOREIGN KEY REFERENCES PRODUCTO(ID),
	IDVENTA INT NOT NULL FOREIGN KEY REFERENCES VENTA(ID),
	CANTIDAD INT NOT NULL,
	PRECIOPARCIAL DECIMAL(10,2) NOT NULL)
	
CREATE TABLE DBO.COMPRA
	(ID INT  PRIMARY KEY NOT NULL IDENTITY(10100001,1),
	IDPROVEEDOR INT FOREIGN KEY REFERENCES PROVEEDOR(ID),
	FECHACOMPRA DATE NOT NULL,
	PRECIOTOTAL MONEY NOT NULL)

CREATE TABLE DBO.DETALLECOMPRA
	(ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	IDPRODUCTO INT NOT NULL FOREIGN KEY REFERENCES PRODUCTO(ID),
	IDCOMPRA INT NOT NULL FOREIGN KEY REFERENCES COMPRA(ID),
	CANTIDAD INT NOT NULL,
	PRECIOPARCIAL DECIMAL(10,2) NOT NULL)



	
--INSERT
	insert into MARCA values ('Samsung','1'),('Topmega','1'),('Acer','1'),('Xiaomi','1'),('Nike','1')
	insert into CATEGORIA values ('Smartphones','1'),('Relojes','1'),('Bicicletas','1'),('Indumentaria','1'),('Farmacia','1')
	insert into VENTA values (37763043,1000)
	insert into PROVEEDOR values ('Multipoint','1')
	insert into PRODUCTO values('Samsung a12',1,1,1,1,1,10,1),('Bicicleta R29 21V',1,1,1,1,1,5,1)
	insert into CLIENTE values ('37763043','Lucas','Barriento',1)
	select*from producto

	



	SELECT CAST('TRUE'AS BIT)--1
	

