CREATE DATABASE COMERCIO_DB
GO
USE COMERCIO_DB
GO
--TABLAS
CREATE TABLE DBO.CLIENTE
	(ID INT PRIMARY KEY NOT NULL,
	NOMBRE VARCHAR(30) NOT NULL,
	APELLIDO VARCHAR(30) NOT NULL,
	ESTADO BIT NOT NULL DEFAULT 1)

CREATE TABLE DBO.MARCA
	(ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	NOMBRE VARCHAR(30) NOT NULL,
	ESTADO BIT NOT NULL DEFAULT 1)

CREATE TABLE DBO.CATEGORIA
	(ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	NOMBRE VARCHAR(30) NOT NULL,
	ESTADO BIT NOT NULL DEFAULT 1)

CREATE TABLE DBO.PROVEEDOR
	(ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	NOMBRE VARCHAR(30) NOT NULL,
	DOMICILIO VARCHAR(50) NOT NULL,
	LOCALIDAD VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	TELEFONO VARCHAR(20) NOT NULL,
	ESTADO BIT NOT NULL DEFAULT 1)

CREATE TABLE DBO.PRODUCTO
	(ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	NOMBRE VARCHAR(50) NOT NULL,
	IDMARCA INT FOREIGN KEY REFERENCES MARCA(ID),
	IDCATEGORIA INT FOREIGN KEY REFERENCES CATEGORIA(ID),
	STOCK INT NOT NULL,
	STOCKMINIMO INT NOT NULL,
	PRECIO MONEY NOT NULL,
	PORCENTAJEGANANCIA DECIMAL(10,2) NOT NULL,
	ESTADO BIT NOT NULL DEFAULT 1)

CREATE TABLE DBO.VENTA
	(ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	IDCLIENTE INT FOREIGN KEY REFERENCES CLIENTE(ID),
	PRECIOFINAL MONEY NOT NULL)

	CREATE TABLE DBO.DETALLEVENTA
	(ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	IDPRODUCTO INT NOT NULL FOREIGN KEY REFERENCES PRODUCTO(ID),
	IDVENTA INT NOT NULL FOREIGN KEY REFERENCES VENTA(ID),
	CANTIDAD INT NOT NULL,
	PRECIOPARCIAL MONEY NOT NULL)
	
CREATE TABLE DBO.COMPRA
	(ID INT  PRIMARY KEY NOT NULL IDENTITY(10100001,1),
	IDPROVEEDOR INT FOREIGN KEY REFERENCES PROVEEDOR(ID),
	FECHACOMPRA DATE NOT NULL,
	PRECIOTOTAL MONEY NOT NULL)
	
CREATE TABLE DBO.DETALLECOMPRA
	(ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	IDPRODUCTO INT NOT NULL FOREIGN KEY REFERENCES PRODUCTO(ID),
	IDCOMPRA INT NOT NULL FOREIGN KEY REFERENCES COMPRA(ID),
	CANTIDAD INT NOT NULL,
	PRECIOPARCIAL MONEY NOT NULL)
	
CREATE TABLE DBO.PROVEEDORES_PRODUCTOS
	(ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	IDPRODUCTO INT NOT NULL FOREIGN KEY REFERENCES PRODUCTO(ID),
	IDPROVEEDOR INT NOT NULL FOREIGN KEY REFERENCES PROVEEDOR(ID)
	)

-- PROCEDIMIENTOS
CREATE PROCEDURE SP_INSERTPROVEEDOR_NUEVOPRODUCTO(@IDPROVEEDOR BIGINT)--despues de agregar un nuevo producto,se agregan los proveedores asociados
AS 
BEGIN
	INSERT INTO PROVEEDORES_PRODUCTOS VALUES((select ident_current('producto')),@IDPROVEEDOR)--ident_current() DEVUELVE EL ULTIMO ID CREADO EN LA TABLA ESPECIFICADA 
END

CREATE PROCEDURE SP_ELIMINAR_PROVEEDORESXIDPRODUCTO(@IDPRODUCTO BIGINT)--elimina un proveedor asociado a un producto
AS
BEGIN
	IF EXISTS (SELECT * FROM PROVEEDORES_PRODUCTOS WHERE IDPRODUCTO=@IDPRODUCTO)
	BEGIN
		DELETE FROM PROVEEDORES_PRODUCTOS WHERE IDPRODUCTO=@IDPRODUCTO
	END
END

CREATE PROCEDURE SP_AGREGAR_ITEMS_COMPRA(
@IDPRODUCTO BIGINT,@CANTIDAD BIGINT,@PRECIOPARCIAL MONEY)
AS
BEGIN
	insert into DETALLECOMPRA values (@IDPRODUCTO,(select ident_current('COMPRA')),@CANTIDAD,@PRECIOPARCIAL)
END
----------------------------------

--INSERT
	insert into MARCA values ('Samsung','1'),('Topmega','1'),('Acer','1'),('Xiaomi','1'),('Nike','1')
	insert into CATEGORIA values ('Smartphones','1'),('Relojes','1'),('Bicicletas','1'),('Indumentaria','1'),('Farmacia','1')
	insert into VENTA values (37763043,1000)
	insert into PROVEEDOR values ('Multipoint','Calle falsa 123','Benavidez','email@multipoint.com','0111556589593', '1')
	insert into PRODUCTO values('Samsung a12',1,1,1,1,15000,10,1),('Bicicleta R29 21V',1,1,1,1,70000,5,1)
	insert into CLIENTE values ('37763043','Lucas','Barriento',1)
	insert into PROVEEDORES_PRODUCTOS values (2,1)
	insert into COMPRA values (1,GETDATE(),100000)
	insert into DETALLECOMPRA values (1,(select ident_current('COMPRA')),1,100000)
	

------------------------------
	SELECT CAST('TRUE'AS BIT)--1
	
	select*from PROVEEDORES_PRODUCTOS

select *from producto where ID in (select IDPRODUCTO from PROVEEDORES_PRODUCTOS where IDPROVEEDOR=@IDPROVEEDOR)

	
	EXEC SP_ELIMINAR_PROVEEDORESXIDPRODUCTO'1'

	select*from PROVEEDOR


	EXEC SP_INSERTPROVEEDOR_NUEVOPRODUCTO @IDPROVEEDOR='3'

	select P.Id, P.Nombre,M.id idMar, M.Nombre Marca,C.id idCat, C.Nombre Categoria, P.Stock, P.StockMinimo, P.PorcentajeGanancia,P.Estado from PRODUCTO P, MARCA M, CATEGORIA C where P.IdCategoria = C.Id and P.IdMarca = M.Id 
	


	