CREATE DATABASE COMERCIO_DB
GO
USE COMERCIO_DB
GO
CREATE TABLE DBO.CLIENTE
	(ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	NOMBRE VARCHAR(30) NOT NULL,
	APELLIDO VARCHAR(30) NOT NULL)

CREATE TABLE DBO.PROVEEDOR
	(ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	NOMBRE VARCHAR(30) NOT NULL)

CREATE TABLE DBO.MARCA
	(ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	NOMBRE VARCHAR(30) NOT NULL)

CREATE TABLE DBO.CATEGORIA
	(ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	NOMBRE VARCHAR(30) NOT NULL)

CREATE TABLE DBO.PRODUCTO
	(ID INT PRIMARY KEY NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	IDMARCA INT FOREIGN KEY REFERENCES MARCA(ID),
	IDCATEGORIA INT FOREIGN KEY REFERENCES CATEGORIA(ID),
	STOCK INT NOT NULL,
	STOCKMINIMO INT NOT NULL,
	PORCENTAJEGANANCIA DECIMAL(10,2) NOT NULL)

CREATE TABLE DBO.VENTA
	(IDVENTA INT PRIMARY KEY IDENTITY(00000001,1) NOT NULL,
	IDCLIENTE INT FOREIGN KEY REFERENCES CLIENTE(ID),
	PRECIOFINAL MONEY NOT NULL)

CREATE TABLE DBO.COMPRA
	(ID INT NOT NULL IDENTITY(00000001,1),
	IDPROVEEDOR INT FOREIGN KEY REFERENCES PROVEEDOR(ID),
	FECHACOMPRA DATE NOT NULL,
	PRECIOTOTAL MONEY NOT NULL)

	insert into MARCA values ('Samsung'),('Topmega'),('Acer'),('Xiaomi'),('Nike')
	insert into CATEGORIA values ('Smartphones'),('Relojes'),('Bicicletas'),('Indumentaria'),('Farmacia')

	insert into PROVEEDOR values ('Multipoint')

	
	